version: "3.8"
services:
  postgres:
    container_name: ${APPLICATION_NAME}-pg
    image: postgres:11.1
    restart: unless-stopped
    networks:
      - app-net
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      PGUSER: ${DATABASE_USERNAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "${DATABASE_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  pgadmin4:
    container_name: ${APPLICATION_NAME}-pgadmin4
    image: dpage/pgadmin4:4.23
    restart: unless-stopped
    networks:
      - app-net
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin4/servers.json:/pgadmin4/servers.json:ro
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  prometheus:
    image: prom/prometheus:latest
    container_name: ${APPLICATION_NAME}-prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  rabbitmq:
    container_name: ${APPLICATION_NAME}-rabbitmq
    image: rabbitmq:3.8.5-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-net:
    driver: bridge
