spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: ${DATABASE_DRIVER}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: env, health, info, metrics, prometheus

info:
  app:
    version: 1.0.0
    name: Contact Us Demo
    camp: Spring Boot Camp
    link: https://albertattard.github.io/spring-boot-camp/
