global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'contact-us'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Points to the laptop
